[package]
name = "nprandom"
version = "0.1.0"
edition = "2021"

[lib]
name = "maze"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
numpy = "0.26"
ndarray = "0.16.1"
rand = "0.9.1"
